app/base/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("keepcount.urls")),
]

app/dtd_calls/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views


app_name = "dtd_calls"

urlpatterns = [
    path("", views.CallCreateView.as_view(), name="call_create"),
    path("<int:pk>/", views.CallDetailView.as_view(), name="call_detail"),
    path("update/<int:pk>/", views.CallUpdateView.as_view(), name="call_update"),
    path("all/", views.CallListView.as_view(), name="call_list"),
    path("pulse/", views.pulse, name="call_pulse"),
]

app/dtd_reports/urls.py
from . import views
from django.urls import path

app_name = "dtd_reports"

urlpatterns = [
    # Template View URLs ---------------------------------------------------------------
    path(
        "call-duration",
        views.CallDurationReport.as_view(),
        name="call-duration-report",
    ),
    path("call-type", views.CallTypeReport.as_view(), name="call-type-report"),
    path(
        "call-referral",
        views.CallReferralReport.as_view(),
        name="call-referral-report",
    ),
    path(
        "request-domain",
        views.RequestDomainReport.as_view(),
        name="request-domain-report",
    ),
    path(
        "total-calls-requests",
        views.TotalCallsRequestsReport.as_view(),
        name="total-calls-requests-report",
    ),
    path("weekly-report", views.WeeklyReportView.as_view(), name="weekly-report"),
    # Data View URLs -------------------------------------------------------------------
    path("call-type/data", views.call_type_report_data, name="call-type-report-data",),
    path(
        "call-duration/data",
        views.call_duration_report_data,
        name="call-duration-report-data",
    ),
    path(
        "call-referral/data",
        views.call_referral_report_data,
        name="call-referral-report-data",
    ),
    path(
        "request-domain/data",
        views.request_domain_report_data,
        name="request-domain-report-data",
    ),
    path(
        "total-calls-requests/data",
        views.total_calls_requests_report_data,
        name="total-calls-requests-report-data",
    ),
    path("weekly-report/data", views.weekly_report_data, name="weekly-report-data"),
    path("weekly-report/csv", views.weekly_report_csv, name="weekly-report-csv"),
]

app/dtd_calls/models.py
from dtd_request.models import domains

from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models


class Agency(models.Model):
    class Meta:
        verbose_name_plural = "Agencies"
        ordering = ["-pk"]

    name = models.CharField(verbose_name="Agency Name", max_length=256)

    def __str__(self):
        return self.name


class Call(models.Model):
    INCOMING = "Incoming"
    OUTGOING = "Outgoing"
    FTP = "FTP"

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    started_at = models.DateTimeField(verbose_name="Call Started")
    ended_at = models.DateTimeField(verbose_name="Call Ended")
    caller_name = models.CharField(
        verbose_name="Caller Name", max_length=256, null=True
    )
    caller_address = models.CharField(
        verbose_name="Caller Street Address", max_length=256, null=True
    )
    caller_city = models.CharField(
        verbose_name="Caller City", max_length=256, null=True
    )
    caller_state = models.CharField(
        verbose_name="Caller State (2-Letter)", max_length=2, help_text="TN", null=True
    )
    caller_zip = models.CharField(
        validators=[RegexValidator(r"^\d{5}$")],
        max_length=5,
        verbose_name="Caller Zip Code",
        help_text="#####",
    )
    caller_number = models.CharField(
        validators=[RegexValidator(r"^\+?1?\d{3}-?\d{3}-?\d{4}$")],
        max_length=17,
        verbose_name="Caller Phone Number",
        help_text="###-###-####",
    )
    caller_email = models.EmailField(verbose_name="Caller Email Address", null=True)
    caller_dob = models.DateField(verbose_name="Caller Date of Birth", null=True, blank=True)
    caller_age = models.IntegerField(verbose_name="Caller Age", null=True)
    caller_gender = models.CharField(
        verbose_name="Caller Gender",
        choices=(("M", "Male"), ("F", "Female"), ("O", "Other")),
        max_length=1,
        null=True,
    )
    caller_household_size = models.IntegerField(
        verbose_name="Caller Household Size", null=True
    )
    call_type = models.CharField(
        max_length=8,
        choices=(
            (INCOMING, "Incoming"),
            (OUTGOING, "Outgoing"),
            (FTP, "Free Tax Prep (Outgoing)"),
        ),
        default="Incoming",
        verbose_name="Type of Call",
    )
    covid_related = models.BooleanField(
        verbose_name="Is this call related to Covid-19?", default=False
    )
    client_referred = models.BooleanField(
        verbose_name="Was this client referred to a provider?", default=False
    )
    referral_id = models.IntegerField(verbose_name="Referral ID", blank=True, null=True)
    referred_agency = models.ForeignKey(
        Agency, on_delete=models.SET_NULL, blank=True, null=True
    )
    notes = models.TextField(verbose_name="Notes", blank=True, null=True)
    followup_notes = models.TextField(
        verbose_name="Followup Notes", blank=True, null=True
    )
    operator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="call_operator",
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="call_assigned_to",
    )
    call_source = models.TextField(
        verbose_name="How did you hear about the UWMS Relief Call Center?",
        max_length=200,
        choices=[
            ("church", "Church/Religious Institution"),
            ("work", "Workplace"),
            ("211", "LINC-211"),
            ("radio", "Radio Ad"),
            ("other", "Other"),
        ],
        null=True,
        blank=True,
    )

    def duration(self):
        diff = self.ended_at - self.started_at
        minutes = divmod(diff.seconds, 60)
        return f"{minutes[0]} minutes, {minutes[1]} seconds"

    def status(self):
        return Call.objects.get(pk=self.id).statuses.latest("id")


class Domain(models.Model):
    call = models.ForeignKey(Call, related_name="domains", on_delete=models.CASCADE)
    domain = models.IntegerField(choices=domains, verbose_name="Service Domain(s)")

    def __str__(self):
        return next(i[-1] for i in domains if i[0] == self.domain)

    def label(self):
        return self.__str__()


class CallStatus(models.Model):
    class Meta:
        ordering = ["-created_at"]

    CONTACTED = "Contacted"
    REFERRED = "Referred"
    INFO = "Shared Information"
    CLOSED = "Closed"
    statuses = ((1, CONTACTED), (2, REFERRED), (3, INFO), (4, CLOSED))

    created_at = models.DateTimeField(auto_now_add=True)
    call = models.ForeignKey(Call, related_name="statuses", on_delete=models.CASCADE)
    status = models.IntegerField(choices=statuses, verbose_name="Call Status")
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="status_updated_by",
    )

    def __str__(self):
        return next(i[-1] for i in self.statuses if i[0] == self.status)

    def label(self):
        return self.__str__()

app/dtd_calls/forms.py
from django import forms
from .models import Call, Domain, CallStatus


class DomainForm(forms.ModelForm):
    class Meta:
        model = Domain
        fields = [
            "domain",
        ]
        widgets = {
            "domain": forms.Select(attrs={"class": "form-control", "required": True})
        }


CallDomainFormset = forms.models.inlineformset_factory(
    Call, Domain, form=DomainForm, extra=1, can_delete=False
)


class CallForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = [
            "started_at",
            "ended_at",
            "call_type",
            "call_source",
            "caller_number",
            "caller_email",
            "caller_name",
            "caller_address",
            "caller_city",
            "caller_state",
            "caller_zip",
            "caller_age",
            "caller_dob",
            "caller_gender",
            "caller_household_size",
            "covid_related",
            "client_referred",
            "referral_id",
            "referred_agency",
            "notes",
        ]

    def __init__(self, *args, **kwargs):
        super(CallForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

        self.fields['caller_dob'].widget.attrs.update({
            'class': 'form-control datetimepicker-input',
            "data-target": "#datetimepicker1",
            "placeholder": "mm/dd/yyyy"
        })
        self.fields["caller_dob"].widget.format = "%m/%d/%Y"
        self.fields["caller_dob"].input_formats = ["%m/%d/%Y"]


class CallStatusForm(forms.ModelForm):
    class Meta:
        model = CallStatus
        fields = [
            "status",
        ]
        widgets = {
            "status": forms.Select(
                attrs={"class": "form-control call-status", "required": True}
            )
        }


CallStatusFormset = forms.models.inlineformset_factory(
    Call, CallStatus, form=CallStatusForm, extra=1, can_delete=False
)


class UpdateCallForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = [
            "caller_number",
            "caller_email",
            "caller_name",
            "caller_address",
            "caller_city",
            "caller_state",
            "caller_zip",
            "caller_age",
            "caller_dob",
            "caller_gender",
            "caller_household_size",
            "covid_related",
            "client_referred",
            "referral_id",
            "referred_agency",
            "call_type",
            "notes",
            "followup_notes",
            "assigned_to",
        ]

    def __init__(self, *args, **kwargs):
        super(UpdateCallForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

        self.fields['caller_dob'].widget.attrs.update({
            'class': 'form-control datetimepicker-input',
            "data-target": "#datetimepicker1",
            "placeholder": "mm/dd/yyyy"
        })
        self.fields["caller_dob"].widget.format = "%m/%d/%Y"
        self.fields["caller_dob"].input_formats = ["%m/%d/%Y"]

app/dtd_calls/views.py
import logging

from .forms import CallForm, UpdateCallForm, CallDomainFormset, CallStatusFormset
from .models import Call, Agency, CallStatus

from datetime import datetime, timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import Count, Sum, DurationField, ExpressionWrapper, F
from django.db.models.functions import TruncDate
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.utils import timezone


class CallCreateView(LoginRequiredMixin, CreateView):
    login_url = "/login/"
    model = Call
    template_name = "dtd_calls/create_call.html"
    form_class = CallForm

    def get_context_data(self, **kwargs):
        data = super(CallCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data["domains"] = CallDomainFormset(self.request.POST)
        else:
            data["domains"] = CallDomainFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        domains = context["domains"]
        other_agency = self.request.POST["other-agency"]
        with transaction.atomic():
            self.object = form.save(commit=False)
            self.object.operator = self.request.user
            if other_agency:
                new_agency = Agency(name=other_agency)
                new_agency.save()
                self.object.referred_agency = new_agency
            self.object.save()
            if domains.is_valid():
                domains.instance = self.object
                domains.save()
            CallStatus(call=self.object, status=1, updated_by=self.request.user).save()
        return HttpResponseRedirect(
            reverse_lazy("dtd_calls:call_detail", kwargs={"pk": self.object.id})
        )


class CallUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/login/"
    model = Call
    template_name = "dtd_calls/update_call.html"
    form_class = UpdateCallForm
    success_url = reverse_lazy("dtd_calls:call_list")

    def get_context_data(self, **kwargs):
        data = super(CallUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data["status"] = CallStatusFormset(self.request.POST)
        else:
            data["status"] = CallStatusFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        status_form = context["status"]
        other_agency = self.request.POST["other-agency"]
        with transaction.atomic():
            self.object = form.save(commit=False)
            if other_agency:
                new_agency = Agency(name=other_agency)
                new_agency.save()
                self.object.referred_agency = new_agency
            self.object.save()
            if status_form.is_valid():
                status_form.instance = self.object
                print(status_form.cleaned_data)
                status = status_form.cleaned_data[0]["status"]
                new_status = CallStatus(
                    call=self.object, status=status, updated_by=self.request.user
                )
                new_status.save()
        return HttpResponseRedirect(
            reverse_lazy("dtd_calls:call_detail", kwargs={"pk": self.object.id})
        )


class CallDetailView(LoginRequiredMixin, DetailView):
    login_url = "/login/"
    model = Call
    template_name = "dtd_calls/detail_call.html"


class CallListView(LoginRequiredMixin, ListView):
    login_url = "/login/"
    model = Call
    template_name = "dtd_calls/list_call.html"
    paginate_by = 25
    ordering = ["-created_at"]

def pulse(request):
    now = datetime.now()
    html = f"<html><body>{now}</body></html>"
    return HttpResponse(html)

app/dtd_calls/templates/dtd_calls/call-referral-report.html
{% extends "dtd_reports/report-nav.html" %}

{% block report %}

<div class="container p-2 bg-light">
  <div class="row">
    <div class="col">
      <canvas id="call-duration-chart" data-url="{% url 'dtd_reports:call-referral-report-data' %}"></canvas>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>
<script>
  $(function() {
    $("#call-referral-report").addClass("active");
  });

  $(function () {

    var $callDurationChart = $("#call-duration-chart");
    $.ajax({
      url: $callDurationChart.data("url"),
      success: function (data) {

        var ctx = $callDurationChart[0].getContext("2d");

        Chart.scaleService.updateScaleDefaults('linear', {
            ticks: {
                min: 0
            }
        });

        new Chart(ctx, {
          plugins: [ChartDataLabels],
          type: 'pie',
          data: {
            labels: data.labels,
            datasets: [
              {
                label: '# of Calls',
                backgroundColor: ['darkturquoise', 'lightgreen'],
                data: data.percents
              }
            ]          
          },
          options: {
            responsive: true,
            legend: {
              position: 'left',
            },
            title: {
              display: true,
              text: 'Percentage of Calls Referred'
            },
            tooltips: {
              callbacks: {
                label: (item, data) => {
                  var i = item.index;                 
                  return  data.labels[i] + ': ' + data.datasets[0].data[i] + '%';
                }
              }
            },
            plugins: {
              datalabels: {
                color: '#ffffff',
                font: {
                  size: 18,
                  weight: 'bold'
                }
              }
            }
          }
        });

      }
    });

  });
</script>

{% endblock %}

app/dtd_calls/templates/dtd_calls/call-report.html
{% extends "dtd_calls/report-nav.html" %}

{% block report %}

<div class="container p-2 bg-light">
  <div class="row">
    <div class="col">
      <canvas id="call-type-chart" data-url="{% url 'dtd_calls:call-type-report-data' %}"></canvas>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script>
  $(function() {
    $("#calls-per-day-report").addClass("active");
  });

  $(function () {

    var $callTypeChart = $("#call-type-chart");
    $.ajax({
      url: $callTypeChart.data("url"),
      success: function (data) {

        var ctx = $callTypeChart[0].getContext("2d");

        Chart.scaleService.updateScaleDefaults('linear', {
            ticks: {
                min: 0
            }
        });

        new Chart(ctx, {
          type: 'bar',
          data: {
            labels: data.labels,
            datasets: [
              {
                label: 'Incoming Calls',
                backgroundColor: 'darkturquoise',
                data: data.incoming_calls
              },
              {
                label: 'Outgoing Calls',
                backgroundColor: 'lightgreen',
                data: data.outgoing_calls
              }
            ]          
          },
          options: {
            responsive: true,
            legend: {
              position: 'top',
            },
            title: {
              display: true,
              text: 'Calls per Day, by Type'
            }
          }
        });

      }
    });

    });
</script>

{% endblock %}

app/dtd_calls/templates/dtd_calls/detail_call.html
{% extends "dtd_request/base.html" %}

{% load static %}

{% block title %}Review Call{% endblock %}

{% block content %}

<div class="container p-2 bg-light">
  <div class="row py-2">
    <div class="col-sm-4">
      <dl>
        <dt><h5>Timestamps</h5></dt>
          <dd> - <b>Record Created: </b>{{ call.created_at }}</dd>
          <dd> - <b>Last Updated: </b>{{ call.updated_at }}</dd>
          <dd> - <b>Call Started: </b>{{ call.started_at }}</dd>
          <dd> - <b>Call Ended: </b>{{ call.ended_at }}</dd>
          <dd> - <b>Last Status: </b>{{ call.status.created_at }}</dd>

        <hr>

        <dt><h5>Caller Information</h5></dt>
          <dd> - <b>Name: </b>{{ call.caller_name }}</dd>
          <dd> - <b>Phone Number: </b>{{ call.caller_number }}</dd>
          <dd> - <b>Email Address: </b>{{ call.caller_email }}</dd>
          <dd> - <b>Address: </b>{{ call.caller_address }}</dd>
          <dd> - <b>City/State/Zip: </b>{{ call.caller_city }}/{{ call.caller_state }}/{{ call.caller_zip }}</dd>
          <dd> - <b>Birth Date: </b>{{ call.caller_dob |  date:"m/d/Y" }}</dd>
          <dd> - <b>Age: </b>{{ call.caller_age }}</dd>
          <dd> - <b>Gender: </b>{{ call.caller_gender }}</dd>
          <dd> - <b>Household Size: </b>{{ call.caller_household_size }}</dd>
      </dl>
    </div>
    <div class="col-sm-4">
      <dd>
        <dt><h5>Call Information</h5></dt>
          <dd> - <b>Type: </b>{{ call.call_type }}</dd>
          <dd> - <b>COVID Related?: </b>{{ call.covid_related }}</dd>
          <dd> - <b>Client Referred?: </b>{{ call.client_referred }}</dd>
          <dd> - <b>Referral ID: </b>{{ call.referral_id }}</dd>
          <dd> - <b>Referred Agency: </b>{{ call.referred_agency }}</dd>
          <dd> - <b>Recorded By: </b>{{ call.operator }}</dd>
          <dd> - <b>Status: </b>{{ call.status }}</dd>
          <dd> - <b>Updated By: </b>{{ call.status.updated_by }}</dd>
          <dd> - <b>Assigned To:</b>{{ call.assigned_to }}</dd>

        <hr>

        <dt><h5>Domains</h5></dt>
          {% for domain in call.domains.all %}
          <dd> - {{ domain }}</dd>
          {% endfor %}
      </dd>
    </div>
    <div class="col-sm-4">
      <dd>
        <dt><h5>Call Notes</h5></dt>
          <dd>{{ call.notes }}</dd>

        <hr>

        <dt><h5>Followup Notes</h5></dt>
          <dd>{{ call.followup_notes }}</dd>
      </dd>
    </div>
  </div>
  <div class="row">
    <div class="col-12 d-flex justify-content-center">
      <a class="btn btn-primary" href="{% url 'dtd_calls:call_create' %}">New Call</a>
    </div>
  </div>
</div>

<script>
  $(function() {
    $("#review-calls").addClass("active");
  });
</script>

{% endblock %}