app/base/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("keepcount.urls")),
]

app/dtd_calls/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views


app_name = "dtd_calls"

urlpatterns = [
    path("", views.CallCreateView.as_view(), name="call_create"),
    path("<int:pk>/", views.CallDetailView.as_view(), name="call_detail"),
    path("update/<int:pk>/", views.CallUpdateView.as_view(), name="call_update"),
    path("all/", views.CallListView.as_view(), name="call_list"),
    path("pulse/", views.pulse, name="call_pulse"),
]

app/dtd_reports/urls.py
from . import views
from django.urls import path

app_name = "dtd_reports"

urlpatterns = [
    # Template View URLs ---------------------------------------------------------------
    path(
        "call-duration",
        views.CallDurationReport.as_view(),
        name="call-duration-report",
    ),
    path("call-type", views.CallTypeReport.as_view(), name="call-type-report"),
    path(
        "call-referral",
        views.CallReferralReport.as_view(),
        name="call-referral-report",
    ),
    path(
        "request-domain",
        views.RequestDomainReport.as_view(),
        name="request-domain-report",
    ),
    path(
        "total-calls-requests",
        views.TotalCallsRequestsReport.as_view(),
        name="total-calls-requests-report",
    ),
    path("weekly-report", views.WeeklyReportView.as_view(), name="weekly-report"),
    # Data View URLs -------------------------------------------------------------------
    path("call-type/data", views.call_type_report_data, name="call-type-report-data",),
    path(
        "call-duration/data",
        views.call_duration_report_data,
        name="call-duration-report-data",
    ),
    path(
        "call-referral/data",
        views.call_referral_report_data,
        name="call-referral-report-data",
    ),
    path(
        "request-domain/data",
        views.request_domain_report_data,
        name="request-domain-report-data",
    ),
    path(
        "total-calls-requests/data",
        views.total_calls_requests_report_data,
        name="total-calls-requests-report-data",
    ),
    path("weekly-report/data", views.weekly_report_data, name="weekly-report-data"),
    path("weekly-report/csv", views.weekly_report_csv, name="weekly-report-csv"),
]

app/dtd_request/templates/dtd_request/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
{% load tz %}

{% timezone "America/Chicago" %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Font Awesome CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


  <!-- Iconic CSS -->
  <link rel="stylesheet" href="{% static 'dtd_request/css/open-iconic-bootstrap.min.css' %}">

  <!-- Favicon -->
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'dtd_request/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'dtd_request/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'dtd_request/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'dtd_request/favicon/site.webmanifest' %}">
  
  <!--Need to load jQuery in the head to support scripting in child templates-->
  <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>

  

  <!-- moment.js and Tempus Dominus for datepickers -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />

  <style type="text/css">
    #navbarSupportedContent > ul > li.nav-item:hover {
      background-color: #ccc !important;
      color: #fff !important;
    }

    #navbarSupportedContent > ul > li.nav-item:hover>a {
      color: #fff !important;
    }
  </style>

  
  <title>{% block title %}Page Title{% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'dtd_request:request' %}">Driving The Dream | Request Services</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item border-left" id="view-my-requests">
          <a class="nav-link" href="{% url 'dtd_request:my_request_search' %}">View My Requests</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item border-left" id="manage-requests">
          <a class="nav-link" href="{% url 'dtd_request:manage' %}">Manage Requests</a>
        </li>
        <li class="nav-item border-left" id="new-call">
          <a class="nav-link" href="{% url 'dtd_calls:call_create' %}">New Call</a>
        </li>
        <li class="nav-item border-left" id="review-calls">
          <a class="nav-link" href="{% url 'dtd_calls:call_list' %}">Review Calls</a>
        </li>
        <li class="nav-item border-left border-right" id="reports">
          <a class="nav-link" href="{% url 'dtd_reports:call-type-report' %}">Reports</a>
        </li>
        {% else %}
        <li class="nav-item border-left"></li>
        {% endif %}
      </ul>
      {% if user.is_authenticated %}
        <a href="{% url 'dtd_request:logout' %}" class="btn btn-danger my-2 my-sm-0 ml-2">
          <img src="{% static 'dtd_request/icons/svg/account-logout-white.svg' %}" class="img-fluid" style="width:1.5em;height:1.3rem;" alt="Logout">
        </a>
      {% else %}
        <a href="{% url 'dtd_request:login' %}" class="btn btn-primary my-2 my-sm-0 ml-2">
          <img src="{% static 'dtd_request/icons/svg/account-login-white.svg' %}" class="img-fluid" style="width:1.5em;height:1.3rem;" alt="Login">
        </a>
      {% endif %}
    </div>
  </nav>
  <div class="container mt-5">
    {% block content %}{% endblock %}
    <div class="row">
      <div class="col-12 text-center"><img class="img-fluid" src="{% static 'dtd_request/img/dtd-logo-wide.jpg' %}" alt="Driving the Dream"></div>
    </div>
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script>
    // Activate tooltips
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
      console.log('Added tooltips!')
    })
  </script>
</body>
</html>
{% endtimezone %}