app/base/urls.py
from django.urls import path, include

urlpatterns = [
    path("", include("keepcount.urls")),
]

app/dtd_reports/urls.py
from . import views
from django.urls import path

app_name = "dtd_reports"

urlpatterns = [
    # Template View URLs ---------------------------------------------------------------
    path(
        "call-duration",
        views.CallDurationReport.as_view(),
        name="call-duration-report",
    ),
    path("call-type", views.CallTypeReport.as_view(), name="call-type-report"),
    path(
        "call-referral",
        views.CallReferralReport.as_view(),
        name="call-referral-report",
    ),
    path(
        "request-domain",
        views.RequestDomainReport.as_view(),
        name="request-domain-report",
    ),
    path(
        "total-calls-requests",
        views.TotalCallsRequestsReport.as_view(),
        name="total-calls-requests-report",
    ),
    path("weekly-report", views.WeeklyReportView.as_view(), name="weekly-report"),
    # Data View URLs -------------------------------------------------------------------
    path("call-type/data", views.call_type_report_data, name="call-type-report-data",),
    path(
        "call-duration/data",
        views.call_duration_report_data,
        name="call-duration-report-data",
    ),
    path(
        "call-referral/data",
        views.call_referral_report_data,
        name="call-referral-report-data",
    ),
    path(
        "request-domain/data",
        views.request_domain_report_data,
        name="request-domain-report-data",
    ),
    path(
        "total-calls-requests/data",
        views.total_calls_requests_report_data,
        name="total-calls-requests-report-data",
    ),
    path("weekly-report/data", views.weekly_report_data, name="weekly-report-data"),
    path("weekly-report/csv", views.weekly_report_csv, name="weekly-report-csv"),
]

app/dtd_reports/models.py
from django.db import models


class WeeklyReport(models.Model):
    week_start = models.DateTimeField(verbose_name="First Day of Report Week")
    domain = models.CharField(max_length=200, verbose_name="TTS Domain")
    calls = models.IntegerField(verbose_name="Number of Calls")
    calls_referred = models.IntegerField(verbose_name="Number of Calls Referred")
    requests = models.IntegerField(verbose_name="Number of Online Requests")
    requests_referred = models.IntegerField(
        verbose_name="Number of Online Requests Referred"
    )

    class Meta:
        managed = False
        db_table = "weekly_report"

app/dtd_reports/views.py
import pytz
import csv
import os

from dtd_calls.models import Call
from dtd_request.models import Request, Domain, domains
from .models import WeeklyReport
from datetime import timedelta, datetime

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, ExpressionWrapper, DurationField, F, Sum, Max
from django.db.models.functions import TruncDate
from django.forms.models import model_to_dict
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.utils import timezone

# =======================================================================================
# region Data Views --------------------------------------------------------------------
# =======================================================================================


def call_type_report_data(request):
    labels = []
    incoming_calls = []
    outgoing_calls = []
    ftp_calls = []
    tz = pytz.timezone("America/Chicago")

    start_date = timezone.now() - timedelta(days=15)
    queryset = (
        Call.objects.filter(created_at__gt=start_date)
        .annotate(date=TruncDate("created_at", tzinfo=tz))
        .values("call_type", "date")
        .annotate(total_calls=Count("date"))
        .order_by("date", "call_type")
    )

    for entry in queryset:
        date_string = entry["date"].strftime("%m/%d/%Y")
        if date_string not in labels:
            labels.append(date_string)
            if len(labels) > len(incoming_calls) + 1:
                incoming_calls.append(None)
            if len(labels) > len(outgoing_calls) + 1:
                outgoing_calls.append(None)
            if len(labels) > len(ftp_calls) + 1:
                ftp_calls.append(None)

        if entry["call_type"] == "Incoming":
            incoming_calls.append(entry["total_calls"])
        elif entry["call_type"] == "Outgoing":
            outgoing_calls.append(entry["total_calls"])
        elif entry["call_type"] == "FTP":
            ftp_calls.append(entry["total_calls"])

    return JsonResponse(
        data={
            "labels": labels,
            "incoming_calls": incoming_calls,
            "outgoing_calls": outgoing_calls,
            "ftp_calls": ftp_calls,
        }
    )


def call_duration_report_data(request):
    labels = []
    incoming_calls = []
    outgoing_calls = []
    ftp_calls = []
    tz = pytz.timezone("America/Chicago")

    start_date = timezone.now() - timedelta(days=15)
    queryset = (
        Call.objects.filter(created_at__gt=start_date)
        .annotate(
            date=TruncDate("created_at", tzinfo=tz),
            duration=ExpressionWrapper(
                F("ended_at") - F("started_at"), output_field=DurationField()
            ),
        )
        .values("call_type", "date")
        .annotate(total_duration=Sum("duration"))
        .order_by("date", "call_type")
    )
    for entry in queryset:
        date_string = entry["date"].strftime("%m/%d/%Y")
        minutes = round(entry["total_duration"].seconds // 60)

        if date_string not in labels:
            labels.append(date_string)
            if len(labels) > len(incoming_calls) + 1:
                incoming_calls.append(None)
            if len(labels) > len(outgoing_calls) + 1:
                outgoing_calls.append(None)
            if len(labels) > len(ftp_calls) + 1:
                ftp_calls.append(None)

        if entry["call_type"] == "Incoming":
            incoming_calls.append(minutes)
        elif entry["call_type"] == "Outgoing":
            outgoing_calls.append(minutes)
        elif entry["call_type"] == "FTP":
            ftp_calls.append(minutes)

    return JsonResponse(
        data={
            "labels": labels,
            "incoming_calls": incoming_calls,
            "outgoing_calls": outgoing_calls,
            "ftp_calls": ftp_calls,
        }
    )


def call_referral_report_data(request):
    queryset = Call.objects.values("client_referred").annotate(
        n=Count("client_referred")
    )
    call_count = Call.objects.count()

    labels = [
        "Referred" if entry["client_referred"] else "Not Referred" for entry in queryset
    ]
    percents = [round((entry["n"] / call_count) * 100) for entry in queryset]

    return JsonResponse(data={"labels": labels, "percents": percents})


def request_domain_report_data(request):
    queryset = (
        Domain.objects.values("domain").annotate(n=Count("domain")).order_by("-n")[:5]
    )

    def to_label(domain: int):
        return next(i[-1] for i in domains if i[0] == domain)

    labels = [to_label(entry["domain"]) for entry in queryset]
    counts = [entry["n"] for entry in queryset]

    return JsonResponse(data={"labels": labels, "counts": counts})


def total_calls_requests_report_data(request):
    incoming_calls = Call.objects.filter(call_type="Incoming").count()
    online_intakes = Request.objects.count()

    labels = ["Incoming Calls", "Online Intakes"]
    counts = [incoming_calls, online_intakes]

    return JsonResponse(data={"labels": labels, "counts": counts})


def weekly_report_data(request):
    current_week_records = WeeklyReport.objects.annotate(
        current_week=Max("week_start")
    ).filter(week_start=F("current_week"))
    return JsonResponse(
        data={"reports": [model_to_dict(i) for i in current_week_records]}
    )


def weekly_report_csv(request):
    weekly_report_records = WeeklyReport.objects.order_by("week_start").all()
    file_name = f"Weekly Call Center Report as of {datetime.now().date()}.csv"

    if not os.path.exists(os.path.join(settings.BASE_DIR, "data")):
        os.makedirs(os.path.join(settings.BASE_DIR, "data"))

    file_path = os.path.join(settings.BASE_DIR, f"data/{file_name}")
    with open(file_path, "w") as output_file:
        writer = csv.writer(output_file, delimiter=",")
        headers = [
            "Week Start",
            "Domain",
            "Calls",
            "Calls Referred",
            "Online Requests",
            "Online Requests Referred",
        ]
        writer.writerow(headers)
        for w in weekly_report_records:
            row = [
                w.week_start,
                w.domain,
                w.calls,
                w.calls_referred,
                w.requests,
                w.requests_referred,
            ]
            writer.writerow(row)

    with open(file_path, "r") as csv_file:
        resp = HttpResponse(csv_file.read(), content_type="application/x-download")
        resp["Content-Disposition"] = f"attachment;filename={file_name}"
    return resp


# =======================================================================================
# endregion ----------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
# region Template Views ----------------------------------------------------------------
# =======================================================================================


class CallTypeReport(LoginRequiredMixin, TemplateView):
    template_name = "dtd_reports/call-type-report.html"


class CallDurationReport(LoginRequiredMixin, TemplateView):
    template_name = "dtd_reports/call-duration-report.html"


class CallReferralReport(LoginRequiredMixin, TemplateView):
    template_name = "dtd_reports/call-referral-report.html"


class RequestDomainReport(LoginRequiredMixin, TemplateView):
    template_name = "dtd_reports/request-domain-report.html"


class TotalCallsRequestsReport(LoginRequiredMixin, TemplateView):
    template_name = "dtd_reports/total-calls-requests-report.html"


class WeeklyReportView(LoginRequiredMixin, ListView):
    model = WeeklyReport
    paginate_by = 100
    template_name = "dtd_reports/weekly-report.html"


# =======================================================================================
# endregion ----------------------------------------------------------------------------
# =======================================================================================

app/dtd_reports/templates/dtd_reports/call-duration-report.html
{% extends "dtd_reports/report-nav.html" %}

{% block report %}

<div class="container p-2 bg-light">
  <div class="row">
    <div class="col">
      <canvas id="call-duration-chart" data-url="{% url 'dtd_reports:call-duration-report-data' %}"></canvas>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>
<script>
  $(function() {
    $("#call-duration-per-day-report").addClass("active");
  });

  $(function () {

    var $callDurationChart = $("#call-duration-chart");
    $.ajax({
      url: $callDurationChart.data("url"),
      success: function (data) {

        var ctx = $callDurationChart[0].getContext("2d");

        Chart.scaleService.updateScaleDefaults('linear', {
            ticks: {
                min: 0
            }
        });

        new Chart(ctx, {
          plugins: [ChartDataLabels],
          type: 'bar',
          data: {
            labels: data.labels,
            datasets: [
              {
                label: 'Incoming Calls',
                backgroundColor: 'rgb(0, 206, 209, 0.7)',
                data: data.incoming_calls
              },
              {
                label: 'Outgoing Calls',
                backgroundColor: 'rgb(144, 238, 144, 0.7)',
                data: data.outgoing_calls
              },
              {
                label: 'FTP Calls (Outgoing)',
                backgroundColor: 'rgb(255, 160, 122, 0.7)',
                data: data.ftp_calls
              }
            ]          
          },
          options: {
            responsive: true,
            legend: {
              position: 'top',
            },
            title: {
              display: true,
              text: 'Total Call Duration per Day, by Type'
            },
            tooltips: {
              callbacks: {
                label: (item) => item.yLabel + " minutes"
              }
            },
            plugins: {
              datalabels: {
                color: '#ffffff',
                font: {
                  size: 18,
                  weight: 'bold'
                }
              }
            }
          }
        });

      }
    });

  });
</script>

{% endblock %}

app/dtd_reports/templates/dtd_reports/call-type-report.html
{% extends "dtd_reports/report-nav.html" %}

{% block report %}

<div class="container p-2 bg-light">
  <div class="row">
    <div class="col">
      <canvas id="call-type-chart" data-url="{% url 'dtd_reports:call-type-report-data' %}"></canvas>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>
<script>
  $(function() {
    $("#calls-per-day-report").addClass("active");
  });

  $(function () {

    var $callTypeChart = $("#call-type-chart");
    $.ajax({
      url: $callTypeChart.data("url"),
      success: function (data) {

        var ctx = $callTypeChart[0].getContext("2d");

        Chart.scaleService.updateScaleDefaults('linear', {
            ticks: {
                min: 0
            }
        });

        new Chart(ctx, {
          plugins: [ChartDataLabels],
          type: 'bar',
          data: {
            labels: data.labels,
            datasets: [
              {
                label: 'Incoming Calls',
                backgroundColor: 'rgb(0, 206, 209, 0.7)',
                data: data.incoming_calls
              },
              {
                label: 'Outgoing Calls',
                backgroundColor: 'rgb(144, 238, 144, 0.7)',
                data: data.outgoing_calls
              },
              {
                label: 'FTP Calls (Outgoing)',
                backgroundColor: 'rgb(255, 160, 122, 0.7)',
                data: data.ftp_calls
              }
            ]          
          },
          options: {
            responsive: true,
            legend: {
              position: 'top',
            },
            title: {
              display: true,
              text: 'Calls per Day, by Type'
            },
            plugins: {
              datalabels: {
                color: '#ffffff',
                font: {
                  size: 18,
                  weight: 'bold'
                }
              }
            }
          }
        });

      }
    });

    });
</script>

{% endblock %}

app/dtd_reports/templates/dtd_reports/report-nav.html
{% extends "dtd_request/base.html" %}

{% load static %}

{% block title %}Call Reports{% endblock %}

{% block content %}

<div class="container p-2 bg-light">
  <div class="row">
    <div class="col">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dtd_reports:call-type-report' %}" id="calls-per-day-report">Calls per Day</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dtd_reports:call-duration-report' %}" id="call-duration-per-day-report">Call Duration per Day</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dtd_reports:request-domain-report' %}" id="request-domains-report">Requests by Domain</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dtd_reports:call-referral-report' %}" id="call-referral-report">Calls Referred</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dtd_reports:total-calls-requests-report' %}" id="total-calls-requests-report">Intakes by Type</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'dtd_reports:weekly-report' %}" id="weekly-report">Weekly Report</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col">
      {% block report %}{% endblock %}
    </div>
  </div>
</div>

<script>
  $(function() {
    $("#reports").addClass("active");
  });
</script>

{% endblock %}

app/dtd_reports/templates/dtd_reports/weekly-report.html
{% extends "dtd_reports/report-nav.html" %}

{% block report %}

<div class="container p-2 bg-light">
  <div class="row mb-2">
    <div class="col-sm-10">
      <p><b>Notes:</b></p>
      <ul>
        <li>'Calls' refers to incoming calls. Outgoing calls are connected to online requests.</li>
        <li>Counts are per week, per domain. A call/request may be counted multiple times if the call/request had multiple domains indicated.</li>
        <li>The date indicated is the date the week started.</li>
      </ul>
    </div>
    <div class="col-sm-2">
      <div class="row d-flex justify-content-end">
        <div class="col d-flex justify-content-end">
          <a href="{% url 'dtd_reports:weekly-report-csv' %}" class="btn btn-primary my-4">Download</a>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class="table table-striped">
        {% for listing in object_list %}
          {% if forloop.first %}
          <tr>
            <th>Week Start</th>
            <th>Domain</th>
            <th class="text-center">Incoming Calls</th>
            <th class="text-center">Calls Referred</th>
            <th class="text-center">Online Requests</th>
            <th class="text-center">Online Requests Referred</th>
          </tr>
          {% endif %}
          <tr>
            <td>{{ listing.week_start }}</td>
            <td>{{ listing.domain }}</td>
            <td class="text-center">{{ listing.calls }}</td>
            <td class="text-center">{{ listing.calls_referred }}</td>
            <td class="text-center">{{ listing.requests }}</td>
            <td class="text-center">{{ listing.requests_referred }}</td>
          </tr>
        {% empty %}
          <h2>No weekly reports.</h2>
        {% endfor %}
      </table>
    </div>
  </div>
  
  <nav aria-label="table-navigation">
    <div class="row">
      <div class="col-sm-2 d-flex justify-content-start">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item"><a href="?page=1" class="page-link">&laquo; first</a></li>
            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">previous</a></li>
          {% endif %}
        </ul>
      </div>

      <div class="col-sm-8 d-flex justify-content-center">
        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
      </div>

      <div class="col-sm-2 d-flex justify-content-end">
        <ul class="pagination">
          {% if page_obj.has_next %}
            <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">next</a></li>
            <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">last &raquo;</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>

<script>
  $(function() {
    $("#weekly-report").addClass("active");
  });
</script>


{% endblock %}